%LET n=100;
%LET miu=5;
%LET sigma=2;
DATA uzd6.normalusis;
DO i=1 TO &n;
Y=&miu+&sigma*NORMAL(10);
OUTPUT;
END;
PROC MEANS DATA=uzd6.normalusis MEAN VAR STD;
OUTPUT OUT=rezultatas MEAN(Y)=vid_y VAR(Y)=dispers_y STD(Y)=std_y;
VAR Y;
PROC UNIVARIATE DATA=uzd6.normalusis CIBASIC (TYPE=TWOSIDED ALPHA=0.01);
VAR Y;
PROC UNIVARIATE DATA=uzd6.normalusis CIPCTLDF (ALPHA=0.01);
VAR Y;
DATA uzd6.normalusis;
SET rezultatas;
pag=sqrt(2/(&n-1))*gamma(&n/2)/gamma((&n-1)/2);
std_nepaslinktas=std_y/pag;
KEEP std_nepaslinktas;
RUN;
