//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class HDDConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static HDDConfig defaultInstance = ((HDDConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HDDConfig())));
        
        public static HDDConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\kuosis\\My Documents\\Downloads\\OS\\OS\\KernelPrimityvesV6." +
            "3\\Operacine sistema\\bin\\Debug\\hdd")]
        public string HDDPath {
            get {
                return ((string)(this["HDDPath"]));
            }
            set {
                this["HDDPath"] = value;
            }
        }
    }
}
