DROP TRIGGER Jole.NaujasDarbuotojoNr#
DROP TRIGGER Jole.NaujasKlientoNr#
DROP TRIGGER Jole.PanaikintiKamb#
DROP TRIGGER Jole.KurGyvena#
DROP TRIGGER Jole.KambarioNr#
DROP TRIGGER Jole.KurGyvena2#
DROP TRIGGER Jole.NaujasGyventojas#
DROP TRIGGER Jole.NaujasGyventojas2#
DROP TRIGGER Jole.NaujasGyventojas3#
DROP TRIGGER Jole.NaujasGyventojas4#
DROP TRIGGER Jole.AtnaujintiGyvent#
DROP TRIGGER Jole.AtnaujintiGyvent2#
DROP TRIGGER Jole.SenasGyventojas#
DROP TRIGGER Jole.Gyventojas#
DROP TRIGGER Jole.NaujasRezervavimas#
DROP TRIGGER Jole.NaujasRezervav#
DROP TRIGGER Jole.AtnaujintiRezerv#
DROP TRIGGER Jole.Sumoketa#
DROP TRIGGER Jole.DienuSkaicius#
DROP TRIGGER Jole.DienuSkaicius2#
DROP TRIGGER Jole.DienuSkaicius3#
DROP TRIGGER Jole.DienuSkaicius4#
DROP TRIGGER Jole.DirbaNuo#
DROP TRIGGER Jole.DirbaNuo2#
DROP TRIGGER Jole.KlientoReg#
DROP TRIGGER Jole.KlientoReg2#
DROP TRIGGER Jole.Rezervavimas#
DROP TRIGGER Jole.Rezervavimas2#