INSERT INTO Jole.Darbuotojai
VALUES (0, 'Petraitis', '1958.11.03', '+37061120001', 'Visa Electron', '1000100010001001', 'Direktorius', 3000, CURRENT DATE)
#
INSERT INTO Jole.Darbuotojai
VALUES (0, 'Jonaitis', '1970.08.12', '+37061120002', 'Visa Electron', '1000100010001002', 'Vadybininkas', 2200, CURRENT DATE)
#
INSERT INTO Jole.Darbuotojai
VALUES (0, 'Adminiene', '1967.07.26', '+37061120003', 'Visa Electron', '1000100010001003', 'Administratore', 1900, CURRENT DATE)
#
INSERT INTO Jole.Darbuotojai
VALUES (0, 'Petraityte', '1979.03.20', '+37061120004', 'Visa Electron', '1000100010001004', 'Sekretore', 1500, CURRENT DATE)
#
INSERT INTO Jole.Darbuotojai
VALUES (0, 'Pastini', '1968.10.30', '+37061120005', 'Visa Electron', '1000100010001005', 'Virejas', 1800, CURRENT DATE)
#
INSERT INTO Jole.Darbuotojai
VALUES (0, 'Ajaksas', '1960.05.17', '+37061120006', 'Visa Electron', '1000100010001006', 'Valytojas', 1200, CURRENT DATE)
#
INSERT INTO Jole.Darbuotojai
VALUES (0, 'Properis', '1962.01.09', '+37061120007', 'Visa Electron', '1000100010001007', 'Valytojas', 1200, CURRENT DATE)
#
INSERT INTO Jole.Darbuotojai
VALUES (0, 'Kaminskas', '1956.12.01', '+37061120008', 'Visa Electron', '1000100010001008', 'Ukvedys', 800, CURRENT DATE)
#
INSERT INTO Jole.Paslaugos
VALUES ('Informacija', 0, 4)
#
INSERT INTO Jole.Paslaugos
VALUES ('Pusryciai', 10, 5)
#
INSERT INTO Jole.Paslaugos
VALUES ('Pietus', 20, 5)
#
INSERT INTO Jole.Paslaugos
VALUES ('Vakariene', 10, 5)
#
INSERT INTO Jole.Paslaugos
VALUES ('Desertas', 5, 5)
#
INSERT INTO Jole.Kambariai 
VALUES (21, 1, 50, 6)
#
INSERT INTO Jole.Kambariai 
VALUES (22, 2, 45, 6)
#
INSERT INTO Jole.Kambariai 
VALUES (23, 3, 40, 6)
#
INSERT INTO Jole.Kambariai 
VALUES (24, 4, 35, 6)
#
INSERT INTO Jole.Kambariai 
VALUES (31, 1, 50, 7)
#
INSERT INTO Jole.Kambariai 
VALUES (32, 2, 45, 7)
#
INSERT INTO Jole.Kambariai 
VALUES (33, 3, 40, 7)
#
INSERT INTO Jole.Kambariai 
VALUES (34, 4, 35, 7)
#