<?xml version="1.0" encoding="utf-8"?>
<Database Name="POA" Class="POADataModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=5.49.217.43;Initial Catalog=POA;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="POAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Workers" Member="Workers">
    <Type Name="Worker">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="department_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_leader" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_department_headmaster" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>